### ISSUE TITLE
egl::Init Assertion failed

### ISSUE THREAD

**Issue by GriffenJBS** [luismreis/node-openvg#1]
Good stuff, I'm thrilled to find your project.  I'm using [node_ssl v0.8.6-pre](https://gist.github.com/3245130) and have install this module, everything seems ok. When I run  sample/hello.js I get the following error. I'm sure it's a simple matter, but it's good to document these things for others to find.

"node: ../src/egl.cc:61: void egl::Init(): Assertion `success >= 0' failed."

**Comment by skerit** [comment]
There doesn't seem to be a `bin/node-pi` binary and I'm getting this error. I'm using a version updated to work with the latest NAN version on nodejs v6.9.0.
